### ISSUE TITLE
please fix your html 

### ISSUE THREAD

**Issue by wotta** [marketingromania/orienteering#3]
Having 2 blanc lines does not make sense.

**Comment by wotta** [comment]
example : https://github.com/marketingromania/orienteering/blob/master/resources/views/clubs.blade.php#L74-L76

**Comment by alexandrucanavoiu** [comment]
Hi, if you want to contribute please just tell us to add you.
This project is only at the initial stage.... and isn't yet ready for production. And about blanc lines... are not a problem... :)

**Comment by wotta** [comment]
It makes no sense to have them there.
Just decided to point a few things out :+1:

**Comment by alexandrucanavoiu** [comment]
Fix it .
